export { default as BannerSection } from "./bannerSection";
export { default as PartnerSection } from "./partnerSection";
export { default as NetworkSection } from "./networkSection";
export { default as AboutSection } from "./aboutSection";
export { default as ProductSection } from "./productSection";
export { default as NewsSection } from "./newsSection";
export { default as CommunitySection } from "./communitySection";
export { default as TeamSection } from "./teamSection";
export { default as JoinSection } from "./joinSection";
